// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWaco0C92eiQMLbluN8a1ZB1zs0nbgoY',
    appId: '1:754829269173:web:938588817edbff2f3986fc',
    messagingSenderId: '754829269173',
    projectId: 'eat-ease-ed6aa',
    authDomain: 'eat-ease-ed6aa.firebaseapp.com',
    storageBucket: 'eat-ease-ed6aa.appspot.com',
    measurementId: 'G-7BVB8JQSLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2otloSpj6EKgTU2040JHXKKJ2OzODc6g',
    appId: '1:754829269173:android:1e8d0f00df4136793986fc',
    messagingSenderId: '754829269173',
    projectId: 'eat-ease-ed6aa',
    storageBucket: 'eat-ease-ed6aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlci98V-gvtlElJYzxKB2xIlvDwee-vOQ',
    appId: '1:754829269173:ios:40fc51e73a5dddf63986fc',
    messagingSenderId: '754829269173',
    projectId: 'eat-ease-ed6aa',
    storageBucket: 'eat-ease-ed6aa.appspot.com',
    iosBundleId: 'com.example.eatease',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlci98V-gvtlElJYzxKB2xIlvDwee-vOQ',
    appId: '1:754829269173:ios:40fc51e73a5dddf63986fc',
    messagingSenderId: '754829269173',
    projectId: 'eat-ease-ed6aa',
    storageBucket: 'eat-ease-ed6aa.appspot.com',
    iosBundleId: 'com.example.eatease',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxWaco0C92eiQMLbluN8a1ZB1zs0nbgoY',
    appId: '1:754829269173:web:adb773e07631ec2c3986fc',
    messagingSenderId: '754829269173',
    projectId: 'eat-ease-ed6aa',
    authDomain: 'eat-ease-ed6aa.firebaseapp.com',
    storageBucket: 'eat-ease-ed6aa.appspot.com',
    measurementId: 'G-HFR5JDRYVB',
  );
}
